# Since transifex-synchronization-source is just a staging branch to control
# updates to Transifex, we need to force merge the translations to master,
# excluding the English source files
name: Translations merge to master

on:
  pull_request:
    types: [closed]
    branches:
      - transifex-synchronization-source

jobs:
  merge-translations:
    if: github.event.pull_request.user.login == 'transifex-integration[bot]' && github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master branch
        uses: actions/checkout@v4
        with:
          ref: master

      - name: Setup Git User
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Force merge translation directories (excluding English)
        run: |
          git fetch --unshallow origin transifex-synchronization-source
          for dir in language/*/; do
            if [ -d $dir ] && [ "$(basename $dir)" != "en" ]; then
              git checkout origin/transifex-synchronization-source -- $dir
              git add $dir
            fi
          done
          git commit -m "[Transifex] Update translations on master"
          git push origin master --force