name: Translations update English source

on:
  workflow_dispatch: 
  schedule:
  - cron: '15 5 * * 1'

permissions: write-all

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: transifex-synchronization-source

      - name: Setup Git User
        run: |
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"

      - name: Update English Source to Transifex
        run: |
          git fetch origin master
          git checkout origin/master -- language/en
          git add language/en
          git commit -m "[Transifex] Update English source files"
          git push origin transifex-synchronization-source --force